services:
  postgres-mohh:
    image: postgres:17.0
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/mohh
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  dns:
    build: ./dns-server
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      - mohh-network

  ea-tos-nwc-bundle-http:
    build: ./ea-tos-server
    image: ea-tos-nwc-bundle-server
    restart: unless-stopped
    command: start-http
    volumes:
      - /var/www/certs:/app/certs
    ports:
      - "80:80"

  ea-tos-nwc-bundle-https:
    image: ea-tos-nwc-bundle-server
    restart: unless-stopped
    command: start-https
    volumes:
      - /var/www/certs:/app/certs
    ports:
      - "443:443"

  mohh-master-server:
    image: ghcr.io/a-blondel/mohh-master-server/mohh-master-server:latest
    restart: unless-stopped
    environment:
      - DB_URL=jdbc:postgresql://postgres-mohh:5432/${DB_NAME}
      - DB_USERNAME
      - DB_PASSWORD
      - TCP_HOST_IP
      - UDP_ENABLED=false
      - TOS_ENABLED=false
      - LOGS=/var/log/mohh
    volumes:
      - app_logs:/var/log/mohh
    ports:
      - "11100:11100"
      - "11181:11181"
      - "11191:11191"
      - "21181:21181"
      - "21191:21191"
      - "21171:21171"
      - "21121:21121"

  mohh-gps:
    image: ghcr.io/a-blondel/mohh-gps-docker/mohh-gps-docker:latest
    privileged: true
    environment:
      - GPS_NAME=${GPS_NAME}
      - GPS_PWD=${GPS_PWD}
      - GPS_ADM_PWD=${GPS_ADM_PWD}
      - GPS_PORT=3658
      - GPS_INSTANCES=10
    ports:
      - "3658-3667:3658-3667/udp"
      - "3688-3697:3688-3697/udp"
    networks:
      - mohh-network

volumes:
  db_data:
  app_logs:

networks:
  mohh-network:
