name: MoHH Server deployment pipeline

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ablondel

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate .env
      run: |
        echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
        echo DB_NAME=mohh_db >> .env
        echo DB_PORT=5432 >> .env
        echo TCP_HOST_IP=${{ secrets.SERVER_IP }} >> .env
        echo GPS_NAME=${{ secrets.GPS_NAME }} >> .env
        echo GPS_PWD=${{ secrets.GPS_PWD }} >> .env
        echo GPS_ADM_PWD=${{ secrets.GPS_ADM_PWD }} >> .env

    - name: Generate dnsmasq.conf
      run: |
        cat << EOF > dns-server/dnsmasq.conf
        address=/pspmoh07.ea.com/${{ secrets.SERVER_IP }}
        address=/pspmoh08.ea.com/${{ secrets.SERVER_IP }}
        address=/wiimoh08.ea.com/${{ secrets.SERVER_IP }}
        address=/tos.ea.com/${{ secrets.SERVER_IP }}
        address=/naswii.nintendowifi.net/${{ secrets.SERVER_IP }}
        EOF

    - name: Clean remote directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: rm -rf /var/www/mohh-master-server/*

    - name: Copy project files to remote server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "."
        target: "/var/www/mohh-master-server"

    - name: Login to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Run Docker Compose on remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /var/www/mohh-master-server
          source .env
          docker-compose down
          docker-compose pull
          docker-compose up --build -d
